### PR TITLE
[zsh] Allow inserting multiple lines from history with CTRL-R

### PR DESCRIPTION
**Pull request by gibfahn**
Allows inserting multiple lines from the history at once.

Preserves the existing behaviour, e.g. moving the cursor to the end of
the input line.

Newline-separates the lines if multiple are specified. I didn't add a
trailing newline to keep compatibility with the existing implementation.

Confirmed this works with `\t` and `\n` chars, and assuming `echo`,
being a zsh builtin, will handle the unescaping adequately.

Fixes: https://github.com/junegunn/fzf/issues/1806
Refs: https://superuser.com/questions/1564346/insert-multiple-lines-from-zsh-history

### CODE REVIEW

**Comment by gibfahn** [comment]
@junegunn got the tests to pass, is there anything else I can do to get this landed? I'm using it myself, and it's been working okay, but keeping it rebased is painful.

**Comment by junegunn** [comment]
Thanks for sharing your solution. But I try to keep the functionality consistent across the three shells we support. So I'm not going to merge a zsh-only solution. So for now, I suggest that you just override this function in your .zshrc.

**Comment by junegunn** [comment]
Also, I'd like to keep the code simple and small, only with the features that can be universally agreed upon. These functions serve as the reference implementation, so I think it's important that we keep them easy to understand. Users who need more features can build and share third-party projects with extra features.

**Comment by gibfahn** [comment]
>So I'm not going to merge a zsh-only solution

Does that mean you'd accept a patch that works on all three shells?

>Also, I'd like to keep the code simple and small, only with the features that can be universally agreed upon

It seems like an arbitrary limitation of Ctrl-R to not support multi-select, considering fzf supports it. I'd have thought the reference implementation would be the one that didn't disable multi-select...

>So for now, I suggest that you just override this function in your .zshrc.

Will do, hopefully it doesn't get out of date and cause conflicts :)

**Comment by rayiik** [comment]
I’m actually trying to do the oposite (get my multi line print one one line in bash
```bash
run-help () {
_varset
_choice=$(rh_com "$_rlvar")
READLINE_LINE="$READLINE_LINE ${_choice#*$'\t'}"
if [[ -n "$READLINE_LINE" ]]; then
  print '%s '"$READLINE_LINE" | \
    tr \\n \\s;
   READLINE_POINT=0x7fffffff; else
   READLINE_POINT=0x7fffffff
fi
clear
fcomclean
}
rh_com () {
  _varset
  _parse_help | _fzcom
}
dequote()
{
    eval printf %s "$1" 2>/dev/null
}
quote()
{
    local quoted=${1//\'/\'\\\'\'}
    printf "'%s'" "$quoted"
}
_parse_help()
{
  varset "$@"
    eval local cmd="$(quote "$_tvar")"
    local line
    {
        case $cmd in
            -) cat ;;
            *) LC_ALL=C "$(dequote "$cmd")" ${2:---help} 2>&1 ;;
        esac
    } |
        while read -r line; do

            [[ $line == *([[:blank:]])-* ]] || continue
            # transform "-f FOO, --foo=FOO" to "-f , --foo=FOO" etc
            while [[ $line =~ \
                ((^|[^-])-[A-Za-z0-9?][[:space:]]+)\[?[A-Z0-9]+([,_-]+[A-Z0-9]+)?(\.\.+)?\]? ]]; do
                line=${line/"${BASH_REMATCH[0]}"/"${BASH_REMATCH[1]}"}
            done
            __parse_options "${line// or /, }"
        done
}
__parse_options()
{
    local option option2 i IFS=$' \t\n,/|'
    # Take first found long option, or first one (short) if not found.
    option=
    local -a array=($1)
    for i in "${array[@]}"; do
        case "$i" in
            ---*) break ;;
            --?*)
                option=$i
                break
                ;;
            -?*) [[ $option ]] || option=$i ;;
            *) break ;;
        esac
    done
    [[ $option ]] || return 0
    IFS=$' \t\n' # affects parsing of the regexps below...
    # Expand --[no]foo to --foo and --nofoo etc
    if [[ $option =~ (\[((no|dont)-?)\]). ]]; then
        option2=${option/"${BASH_REMATCH[1]}"/}
        option2=${option2%%[<{().[]*}
        printf '%s\n' "${option2/=*/=}"
        option=${option/"${BASH_REMATCH[1]}"/"${BASH_REMATCH[2]}"}
    fi
    option=${option%%[<{().[]*}
    printf '%s\n' "${option/=*/=}"
}

_fzcom () {
_varset
  fzf  \
      --ansi --phony --query "$_iniquery" \
      --preview="{ cnat; echo $_rlvar '{+}' 2>/dev/null ; fline ; \
      moreman $_tvar 2>/dev/null | \
      rg  --no-filename \
      -C 4  --no-line-number \
      -e '{}' 2>/dev/null; } " \
  --preview-window=right:65:wrap \
  --info=default \
  --bind='ctrl-a:preview-page-up' \
  --bind='ctrl-s:preview-page-down' \
  --bind='ctrl-u:half-page-up+refresh-preview' \
  --bind='ctrl-d:half-page-down+refresh-preview' \
  --bind='alt-u:page-up+refresh-preview' \
  --bind='alt-h:backward-char+refresh-preview' \
  --bind='alt-l:forward-char+refresh-preview' \
  --bind='alt-d:page-down+refresh-preview' \
  --bind="alt-1:execute(printf {})+refresh-preview" \
  --bind="alt-2:toggle+replace-query" \
  --bind="alt-3:execute(printf {q})+refresh-preview" \
  --bind="alt-h:preview(moreman $_tvar)" \
  --bind="alt-n:preview:'moreman {} | rg {q} -C4  \
          --passthru --no-filename'" \
  --no-clear \
  --bind="f9:preview:'cnat; moreman {} | rg {q} -C4 --no-filename \
  --passthrur'+refresh-preview" \
  --phony
}
bind -m vi-insert -x '"\eo":run-help'
bind -m emacs -x '"\eo":run-help'
```
Each option selected end up on a new line so somewhere in their is a multi shell solution? (Bash) or at least something fun to play with

**Comment by gibfahn** [comment]
>Can’t you just add a —multi flag? I’m actually trying to do the oposite (get my multi line print one one line in bash

No, I tried that first, but the shell function only takes the first line.

**Comment by rayiik** [comment]
Ahh

**Comment by gibfahn** [comment]
I keep this branch up-to-date, but for anyone else coming across this, the way to use this version is to duplicate the function in this PR branch in your zshrc somewhere ([example](https://github.com/gibfahn/dot/blob/75074f76a488b13e6ca03d6d554e122ec496e699/dotfiles/.config/zsh/deferred/deferred.zsh#L422)) and then bind Ctrl-R to your widget ([example](https://github.com/gibfahn/dot/blob/75074f76a488b13e6ca03d6d554e122ec496e699/dotfiles/.config/zsh/deferred/deferred.zsh#L526)).

**Comment by cohml** [comment]
@junegunn This discussion is three years old now. Just confirming that reimplementing the original function to allow multiple selection is still the best way to allow multiple selections for history search?

**Comment by junegunn** [comment]
I would accept a patch that implements the behavior consistently on all three shells if it doesn't increase the LoC too much.

**Comment by gibfahn** [comment]
Rebased on master to support the new [multi-line](https://junegunn.github.io/fzf/tips/processing-multi-line-items/) feature in 0.53.0.

I don't know enough about bash or fish to know how feasible an implementation would be there, but this has been working great for me for 4 years now, and going back to single-select Ctrl-R feels like a real regression.

**Pull request closed without merging**
