### PR TITLE
[shell] zsh completion for the Debian package manager (aptitude or `apt`)

### PR DESCRIPTION
**Pull request by sim590**
This is inspired by the efforts that led to writing the small snippet found at https://github.com/krickelkrakel/fzf-apt.

### CODE REVIEW

**Comment by sim590** [comment]
After thinking about it. Maybe this contribution should be a good fit for the Debian package. I guess I could make a PR [there][deb]. What do the developers think? 

[deb]: https://salsa.debian.org/debian/fzf/-/tree/master/debian

**Comment by sim590** [comment]
I have prepared [patch for the debian package][patch]. Therefore, I could close this PR if that is more appropriate to merge in the Debian package.

[patch]: https://salsa.debian.org/sim590-guest/fzf/-/commit/1c892d291baaa40ff3f0581a1a25a682c4a59ca4

**Comment by junegunn** [comment]
Thanks, but I decided not to accept more completion implementations because it's just not possible for me to maintain ever-increasing number of features for three different shells.

**Comment by sim590** [comment]
@junegunn Alright. This is fine, but what about the Debian package? Would you at least accept the patch for the Debian package as aptitude is fundamental element of Debian?

**Comment by junegunn** [comment]
I'm not a maintainer of the Debian package.

**Comment by sim590** [comment]
@junegunn sorry. You're right. I misread the page. Thanks for your answers.

**Comment by junegunn** [comment]
No problem. Take care.

**Pull request closed without merging**
