### PR TITLE
replace perl with bash in the bash history widget

### PR DESCRIPTION
**Pull request by step-**
While awk is POSIX, perl isn't pre-installed on all *nix flavors. This commit replaces perl with a bash script to eliminate dependency on perl.

This commit passed the current test suite with zero errors :
* `make error` => all test sections 'ok'
* `make docker-test` => Finished in 52.150847s, 4.1227 runs/s, 36.0684 assertions/s. 215 runs, 1881 assertions, 0 failures, 0 errors, 0 skips

See also:  #3295 (same idea replacing awk for perl).

I manually tested this commit on macOS Catalina with bash 3.2, and Linux with bash 3.2 and 4.4. While testing on Linux I reported issue #3309.

Note: This commit needs bash support for associative arrays, available since bash 4, to filter out duplicate history items. On macOS, where 3.2 is the default bash version, fzf will not de-duplicate items unless a newer bash version is installed.

### CODE REVIEW

**Comment by step-** [comment]
The integration test action is still failing on the same ruby test. I noticed another difference in the test setup: the action runs ruby tests with `LC_ALL=C`, unlike the DockerFile.

**Comment by junegunn** [comment]
Thanks for working on this. But I don't think this is going to make it. I liked your previous awk version because the required code change was minimal, but that is clearly not true here; I don't want to maintain these extra code lines just for a fairly small number of users.

The real deal breaker is the performance. I have 170K+ entries in my command history, and with the original Perl version, the processing is instantaneous, but with this version, it takes longer than a minute to fully process the list, and that is not acceptable.

**Comment by step-** [comment]
> Thanks for working on this. But I don't think this is going to make it.
> The real deal breaker is the performance.

I would do the same in your place.

> I liked your previous awk version because the required code change was minimal.

I liked it too better than this version but the deal breaker with macOS awk is that I know no way to ascertain the last character read in streaming mode. If I had that in my pocket the awk script could work in macOS too with minimal changes.  I will keep thinking of a way to do it with awk, which is a favorite tool of mine.

> I have 170K+ entries in my command history.

Wow. Good to know to raise to the challenge!

**Comment by step-** [comment]
@glensc, TLDR; <https://github.com/junegunn/fzf/pull/3313#issuecomment-1731031927>

**Pull request closed without merging**
