### PR TITLE
[vim] Detect fzf within wsl on Windows

### LINKED ISSUE #1191: Is it possible fzf on WSL work with GVim in Windows
- Category
    - [x] fzf binary
    - [ ] fzf-tmux script
    - [ ] Key bindings
    - [ ] Completion
    - [x] Vim
    - [ ] Neovim
    - [ ] Etc.
- OS
    - [ ] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [x] Windows Subsystem for Linux
    - [ ] Etc.
- Shell
    - [x] bash
    - [ ] zsh
    - [ ] fish

I have installed fzf on WSL and it works well, also have Vim 8.0 has terminal feature
Is that possible fzf on WSL work with gvim on Windows?

### PR DESCRIPTION
**Pull request by janlazo**
Close #1191

See the commit message for more info.
@rickywu Can you check if this works?

### CODE REVIEW

**Comment by janlazo** [comment]
@rickywu Can you try again?

**Comment by janlazo** [comment]
@rickywu Can you provide the full error log and any custom config you use for fzf? Also, can you test if you can run batchfiles (*.cmd, *.bat) within wsl.exe and whether it accepts `\r\n` or not?

**Comment by janlazo** [comment]
@rickywu Do you have wslpath? See https://github.com/Microsoft/WSL/issues/1834#issuecomment-298984386

**Comment by rickywu** [comment]
wsl.exe accept shell script with both dos/unix format

set shell=cmd.exe works well but set shell=wsl.exe not work and If I issue :FZF command just run vimrun and flash across, I only can capture error by print screen in time

I tried use BreakPts to debug but got some error message about not found script in current path

**Comment by rickywu** [comment]
If you need Windows env, I'll try deploy an AWS windows if available

**Comment by janlazo** [comment]
@rickywu If you don't set `shellredir` (use default value for cmd.exe), does it do anything?

Is this enough to run wsl bash using the default settings on GVim?
```
set shell=wsl.exe
set shellpipe=|
```

**Comment by rickywu** [comment]
It's enough but still has problem,
I only set shell=wsl.exe also has problem.

I captured error msg, it's about unexpected EOF
fzf

**Comment by janlazo** [comment]
Sorry, I forgot `shellcmdflag`. I'll edit my previous post. Mention anything else I missed as we go.

**Comment by rickywu** [comment]
unexpected EOF while looking for matching `"'
syntax error: unexpected end of file

**Comment by janlazo** [comment]
I guess it doesn't use `CommandLineToArgW` (for Neovim users, see `:h jobstart` for more info).
All arguments to wsl must be passed as one whole string.

Using bash.exe (msysgit), I get the following:
```dosbatch
> bash -c \"echo\" a b
/usr/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/usr/bin/bash: -c: line 1: syntax error: unexpected end of file
> bash -c "\"echo\" a b"
a b
```

**Comment by janlazo** [comment]
How about now?

**Comment by rickywu** [comment]
the same problem, I jsut set shell=wsl.exe

**Comment by rickywu** [comment]
applied your changes but the same problem

**Comment by janlazo** [comment]
Minimal vimrc for gvim

```
set rtp+=~/.fzf
```

Assuming the user git-clone the fzf repo in both home directory (Windows, WSL) and fzf (wsl) is in user's bin/, this should be enough. Tested this on WSL.

**Comment by rickywu** [comment]
I tested as I said it's running in cmd but not in wsl

my vimrc:
set rtp+=~/.fzf
set shell=wsl.exe

still the same problem, also test 
set rtp+=~/.fzf
set shell=wsl.exe
set shellxquote = "

I verified .fzf is under C:/Users/Ricky(Windows) and /home/ricky(WSL)

**Comment by janlazo** [comment]
I haven't set `shellxquote` and `shellquote` for cmd.exe yet. I'll  still have to test with `set shell=wsl.exe`.

**Comment by janlazo** [comment]
`fzf#wrap` temporarily sets the shell now so `fzf#shellescape` should work as expected. Setting the shell to something else caused it to use the default `shellescape` from Vim so none of the arguments were escaped properly if I set the shell to anything but cmd.exe prior to running `:FZF`.

**Comment by rickywu** [comment]
nice, works fine, thank you.

**Comment by janlazo** [comment]
@junegunn Can you review the changes?

**Comment by rickywu** [comment]
someone can merge the wsl ag support for fzf.vim?

**Comment by janlazo** [comment]
@rickywu That's a different issue and the changes you propose for `Ag` don't have to be in the fzf.vim repo. You have the autoload functions from autoload/fzf/vim.vim in the fzf.vim repo to define your new commands.

**Comment by rickywu** [comment]
Works well

**Comment by janlazo** [comment]
@junegunn I'm done with my changes. If you don't want to support running fzf (wsl) for GVim (Windows), then consider merging the patch for `fzf#wrap`.

**Comment by janlazo** [comment]
Closing because of lack of interest.

**Pull request closed without merging**
