### PR TITLE
vim: do not use lcd always when temporarily changing dir

### PR DESCRIPTION
**Pull request by blueyed**
Fixes https://github.com/junegunn/fzf/issues/1085.

### CODE REVIEW

**Comment by blueyed** [comment]
@junegunn 
Ping.
I've noticed this issue again after switching aways from this branch/patch, mostly since I have a `haslocaldir()` indicator in my statusline.  It is not nice to set a local dir, which is sticky (and inherited) to/from a window.

**Comment by blueyed** [comment]
It might get improved to skip the "cd" altogether if it is not necessary, but that should be done separately (i.e. I have not looked into it regarding this now).

**Comment by junegunn** [comment]
Is this a work in progress? I can see a few obvious problems in the patch.

**Comment by blueyed** [comment]
@junegunn 
Please comment then - the patch is rather old and I've been using it since.

**Pull request closed without merging**
