### PR TITLE
update plug option in readme

### PR DESCRIPTION
**Pull request by pruett**
i received an error when using the settings in the readme. changing the `dir` option to `rtp` fixed installation.

### CODE REVIEW

**Comment by junegunn** [comment]
No, `dir` is right in this case.

- `dir` designates the directory where the plugin will be installed. If not given, it's `g:plug_home` (which is usually `~/.vim/plugged`) + the name of the plugin.
- `rtp` is only used when the plugin does not follow the standard directory structure.

**Comment by pruett** [comment]
thanks for the response,

i'm still confused...
`brew install fzf` installs fzf, so wouldn't I want to point to where homebrew installed it, or is it different when installing a vim plugin?

**Comment by pruett** [comment]
The following seems to work, although it installs the first plugin to `~/.fzf` even though `g:plug_home` is `~/.vim/plugged`

```vim
call plug#begin()
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()
```

**Comment by junegunn** [comment]
I guess the description can be confusing to the users without enough knowledge of Vim.

I just updated the README page, hope it helps.

https://github.com/junegunn/fzf#as-vim-plugin

**Comment by junegunn** [comment]
> although it installs the first plugin to ~/.fzf

I think you're somehow confused, it doesn't.

**Comment by pruett** [comment]
thanks @junegunn ! That clears it up a bit.

**Pull request closed without merging**
