### PR TITLE
[vim] Use cmd.exe in Windows

### PR DESCRIPTION
**Pull request by janlazo**
When running Vim on Windows,
- use cmd.exe as launcher and shell
- enable shellslash within s:cmd()
- don't escape ' ' and '\\' for paths

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks. Let me review the commit. By the way, we don't use `l:` prefix for local variables. Can you remove the prefixes for consistency?

**Comment by junegunn** [comment]
I haven't tried running Vim plugin for fzf on Windows, and never expected it to work correctly. Can you share your overall experience?

**Comment by janlazo** [comment]
With this PR, it works on file paths if without spaces or not network drives (it breaks on `C:\` ).
It works fine if running fzf, via the Vim plugin, within the home directory (because of `~` expansion).
`:FZF` redraws the entire screen for cmd.exe to run fzf and it behaves as expected when selecting files/directories (even with spaces) to open.

To run terminal Vim, I use ConEmu with Powershell (to minimize file path issues).
I used cmd.exe in the PR because Powershell has long startup time.

**Comment by janlazo** [comment]
For now, in this PR, `FZF` and `FZF!` commands behave the same on terminal Vim in Windows because I did not set the geometry for cmd.exe similar to the xterm_launcher.

**Comment by junegunn** [comment]
Thanks for the explanation. Merged, thanks!

**Pull request merged**
