### PR TITLE
[bash] Fire command directly with CTRL-X in CTRL-R

### PR DESCRIPTION
**Pull request by 4z3**
This PR adds the ability to choose between direct execution and prior editing in CTRL-R for bash.

I'm not sure whether this implementation is acceptable as it is quite hacky and requires two dedicated readline bindings, but as demand for this feature seemed quite high, I've created a PR anyway =)

The trick used is to bind a command (to CTRL-O) that inspects the readline buffer and rebinds another binding (CTRL-P) to either accept a line or do nothing. The rebinding happens if the readline buffer contains a "magic suffix". `__fzf_history__`, in turn, adds the suffix based on the key used to make a selection. By default Enter allows the user to edit the selection, and CTRL-X will execute it immediately, i.e the same way [it was proposed for zsh](https://github.com/junegunn/fzf/issues/477#issuecomment-230338992). As [some users](https://github.com/junegunn/fzf/issues/477#issuecomment-444053054) (me included) prefer to execute by default instead, the keys to choose between execution and editing have been made configurable, e.g.:
```bash
FZF_CTRL_R_EDIT_KEY=ctrl-e
FZF_CTRL_R_EXEC_KEY=enter
```

Related #477

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks for your interest in the project.

Due to increasing maintenance burden, I decided not to add more options to the key bindings this repository provides. Ensuring consistent, stable user experience across three different shells – bash, zsh, and fish – turned out to be quite painful and has taken up much of my time.

So instead of having this merged to this repository, I suggest that you create a separate "plugin" with extended features and options, so that the users can optionally install your bindings if they want.

```sh
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# Load your plugin to override the bindings
```

**Comment by markmcd** [comment]
If you turned this into a plugin, I'd love to use it. Could you share a link here so other Google-searchers can find it?

**Comment by 4z3** [comment]
This PR's code has been copied to [4z3/fzf-plugins](https://github.com/4z3/fzf-plugins).

**Comment by nhooyr** [comment]
This was quite easy in zsh.

See https://github.com/nhooyr/dotfiles/blob/92623b7a3e9fa421d191f6c2bb77de4ce60aa367/zsh/fzf.zsh#L48-L61

**Pull request closed without merging**
