### PR TITLE
add support to nil-byte separated input strings, closes #121

### LINKED ISSUE #121: Accept input separated by NUL bytes
This would be useful with `find`'s `-print0`.

### PR DESCRIPTION
**Pull request by dullgiulio**
Simplified reader and added a configurable delimiter. Added "--null" option to interface.

Not sure I added the help line in the right place. Feel free to fix it yourself.

### CODE REVIEW

**Comment by junegunn** [comment]
Aha, so `ReadString` doesn't suffer the problem of fixed buffer size of 64kb, right? That's nice. Thanks. I'll have to add a test case and update man page before merging it.

**Comment by dullgiulio** [comment]
AFAIK the 64k problem is only in the Scanner. See: http://golang.org/src/bufio/bufio.go#L358 for ReadString implementation. It's similar to what you did.

I also fixed the spacing and period and that made the build fail?

**Comment by junegunn** [comment]
Probably not. Travis CI has been flaky due to its reliance on timeouts and tmux send-keys.

**Comment by junegunn** [comment]
By the way, can you squash the commits into one? I'll do the rest of the job later in the day or tomorrow.

**Comment by dullgiulio** [comment]
Squashed. Let me know if you need anything more here.

**Comment by junegunn** [comment]
Merged to master, thanks!
I'll update the man page when I release the next version.

**Pull request merged**
