### PR TITLE
Occur a Error in Vim which &encoding is cp932

### PR DESCRIPTION
**Pull request by rbtnn**
__error screenshot__
スクリーンショット 2020-10-27 225528

__solution of this PR__
* do not use multibyte characters in plugin/fzf.vim

I think that maybe this PR resolve https://github.com/junegunn/fzf/pull/2224 .

### CODE REVIEW

**Comment by rbtnn** [comment]
I tried following patterns on Windows 10 and gVim(version 8.2.1900) and fzf.vim included this PR.

__encoding=utf-8 & ambiwidth=double__
image

__encoding=utf-8 & ambiwidth=single__
image

__encoding=cp932 & ambiwidth=double__
image

__encoding=cp932 & ambiwidth=single__
image

**Comment by junegunn** [comment]
Thanks, but this code will soon be replaced by the extended `--border` option of the upcoming version of fzf.

- https://github.com/junegunn/fzf/commits/devel
- https://github.com/junegunn/fzf/commit/2e8e63fb0b3b62e89472eebe9e86578598e1a541

**Comment by rbtnn** [comment]
I got it. thank you for your reply.

**Comment by junegunn** [comment]
I just released fzf 0.24.0.

**Pull request closed without merging**
