### PR TITLE
Use go modules and simplify build

### PR DESCRIPTION
**Pull request by rumpelsepp**
This patch introduces the new and shiny go modules to the build system. Third party libraries are now handled out of the box by `go`. I added a `GO` variable to the Makefile such that the name of the `go` tool can be overwritten via, for instance, an environmental variable.

Since it is not needed any more, I removed `glide`.

``` text
$ make GO=go1.11
GOARCH=amd64 go1.11 build -a -ldflags "-X main.revision=ef195d6 -w -extldflags=" -tags "" -o target/fzf-linux_amd64
go: finding github.com/codegangsta/cli v0.0.0-20171128035504-c6af8847eb2b
go: finding github.com/mattn/go-runewidth v0.0.0-20170201023540-14207d285c6c
go: finding github.com/gdamore/encoding v0.0.0-20151215212835-b23993cbb635
go: finding github.com/mattn/go-shellwords v1.0.3
go: finding github.com/mitchellh/go-homedir v0.0.0-20161203194507-b8bc1bf76747
go: finding github.com/lucasb-eyer/go-colorful v0.0.0-20170223221042-c900de9dbbc7
go: finding github.com/gdamore/tcell v0.0.0-20170915061752-0a0db94084df
go: finding golang.org/x/sys v0.0.0-20170529185110-b90f89a1e7a9
go: finding golang.org/x/text v0.0.0-20170530162606-4ee4af566555
go: finding gopkg.in/yaml.v2 v2.0.0-20171116090243-287cf08546ab
go: finding github.com/mattn/go-isatty v0.0.0-20160806122752-66b8e73f3f5c
go: finding github.com/Masterminds/vcs v1.12.0
go: finding golang.org/x/crypto v0.0.0-20170728183002-558b6879de74
go: finding github.com/Masterminds/semver v1.4.0
go: downloading github.com/mattn/go-shellwords v1.0.3
go: downloading github.com/mattn/go-isatty v0.0.0-20160806122752-66b8e73f3f5c
go: downloading golang.org/x/crypto v0.0.0-20170728183002-558b6879de74
go: downloading github.com/mattn/go-runewidth v0.0.0-20170201023540-14207d285c6c
go: downloading golang.org/x/sys v0.0.0-20170529185110-b90f89a1e7a9
```

### CODE REVIEW

**Comment by rumpelsepp** [comment]
I also updated the travis config to actually use a go test environment rather than a ruby one.

**Comment by rumpelsepp** [comment]
I must think of a way how to include the remaining tests. So, this is not ready to merge yet.

**Comment by rumpelsepp** [comment]
This pull request is ready to go.

**Comment by rumpelsepp** [comment]
AFAIK `go mod init` migrates dependencies from glide, govendor, ... automatically. I updated the dependencies with `make update` after initializing the module and only committed the updated version.

**Comment by junegunn** [comment]
Merged, thanks!

**Comment by rumpelsepp** [comment]
Nice, thanks!

**Pull request merged**
