### PR TITLE
Fix #2381 kill running processes by FZF_DEFAULT_COMMAND or reloaded command on terminate

### LINKED ISSUE #2381: fzf doesn't kill running processes by FZF_DEFAULT_COMMAND or reloaded command
- [x] I have read through the manual page (`man fzf`)
- [x] I have the latest version of fzf
- [x] I have searched through the existing issues

## Info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Etc.
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish
    
## Problem / Steps to reproduce
Fzf doesn't kill FZF_DEFAULT_COMMAND execution.

```
% cat > /tmp/script.sh 
#!/bin/bash

while :; do
    date >> /tmp/output
    date
    sleep 1
done
# Ctrl-D

% FZF_DEFAULT_COMMAND=/tmp/script.sh fzf
...
abort or accept

% tail -F /tmp/output
2021年  3月  6日 土曜日 17:25:33 JST
2021年  3月  6日 土曜日 17:25:34 JST
2021年  3月  6日 土曜日 17:25:35 JST
2021年  3月  6日 土曜日 17:25:36 JST
# Keep printing ...

% pgrep -f /tmp/script.sh
3113
```

I use some script with FZF_DEFAULT_COMMAND which loads data from the internet with some batch until no more data.
(I use a script to fetch JIRA tickets which is assigned me and browse them in fzf, for example)
It's not good to remain such process after accept or abort.

### PR DESCRIPTION
**Pull request by bitterfox**
See #2381 also
I'd like to introduce shutdown hook for Terminal and kill process bound in the reader.

### CODE REVIEW

**Comment by bitterfox** [comment]
Fixing test...

**Comment by bitterfox** [comment]
Hmm, somehow this PR doesnt work well with tmux. Let me make this draft once

**Comment by bitterfox** [comment]
About tmux, somehow it's replaced /fzf/bin/fzf with the latest upstream version in my docker container.
After some tweak, my local docker-based test works.

Still don't know why tests for fish are failing.

**Comment by junegunn** [comment]
Thanks for the patch. But I'd like to take a different approach of handling `os.Exit` in Core module to minimize code changes. I'll cherry-pick your test cases and push it to the master.

**Comment by junegunn** [comment]
Pushed to master. Thanks.

I'll have to investigate why the test cases are still failing while `make docker-test` on my machine passes.

**Comment by bitterfox** [comment]
Thank you! Whatever fixes the problem, it works for me!

**Comment by bitterfox** [comment]
@junegunn , is the latest master working correctly?

It blocks to terminate fzf forever when quit fzf session still reading.
```
# fzf on a directory contains many files
% find | fzf
# Ctrl-c or enter while fzf immidiate after fzf start
# blocks
# Ctrl-z
^Z
zsh: done       find | 
zsh: suspended  fzf
# So fzf doesn't exit while find is finished
```

```
% seq 1 100000000 | fzf
# Ctrl-c or enter while fzf immidiate after fzf start
```

Could you check?

**Comment by bitterfox** [comment]
https://github.com/junegunn/fzf/blob/9fe2393a007fd3771f3e6b7badf4c1c2686c065d/src/terminal.go#L2143-L2150

This doesn't release mutex?

**Comment by junegunn** [comment]
Yeah, it's broken. I'll look into it. I thought not releasing the lock would prevent further screen updates, but it's not working as expected.

**Comment by junegunn** [comment]
Fixed on master. Let me know if you still see issues, thanks!

**Comment by junegunn** [comment]
It should be fixed now 😌

**Comment by bitterfox** [comment]
Thank you! Confirmed it fixed and it's working well now!

**Pull request closed without merging**
