### PR TITLE
replace perl with awk in the bash history widget

### PR DESCRIPTION
**Pull request by step-**
While awk is POSIX, perl isn't pre-installed on all *nix flavors. This commit replaces perl with awk thus it eliminates the perl dependency.

This commit passed the current test suite with zero errors :
* `make error` => all test sections 'ok'
* `make docker-test` => Finished in 50.929904s, 4.1822 runs/s, 35.3427 assertions/s. 213 runs, 1800 assertions, 0 failures, 0 errors, 0 skips

See also:  #2777 #1934 # #3077 #2260

Test suite was executed with ruby 3.2.2, minitest 5.18.0, and tmux 3.3a. The current [Dockerfile](https://github.com/junegunn/fzf/blob/94999101e358385f3ca67a6ec9512f549196b802/Dockerfile) runs with older ruby and minitest versions.

Note: unlike the original perl script, which gets `$HISTCOUNT` from the environment, this awk script reads the initial history count from line 1 of stdin. Then follow the history list, and finally a `\t`. The reason for `\t` is to fix a small, pre-existing issue I noticed while developing this patch (see the next comment for additional information).

### CODE REVIEW

**Comment by step-** [comment]
**side note about a side issue**

The commit message mentions a small issue that I uncovered while developing this PR.  I believe the issue is unrelated to this patch.

It's a small issue, mainly cosmetic: when the first element of the history list is displayed in fzf's search window, the element ends with a dandling LF character.  To reproduce this issue I removed `~/.bash_history` in a terminal, then started bash in another terminal, ran a command, like `ls`, finally pressed C-R to start the fzf search history widget.

This commit implements a work-arond to make the dandling LF disappers from the search history window. A `\t` is appended to awk's input stream. The awk script interprets the dangling `\n` (LF) followed by `\t` as a record separator (`RS`). The end result is an empty line, which disappears in the search history window.

**Comment by junegunn** [comment]
Thanks for the patch, but it doesn't work with the awk from macOS. To make it work, I had to use GNU awk (gawk) which must be separately installed.

image

**Comment by step-** [comment]
I can take a look at macOS compatibility, if you're interested in this patch. Are you?
Nothing stands out to me as being gnu-ish in the awk script... it's very basic awk, tested on busybox awk, gawk --posix and mawk. But again, I can take a look at macOS. What's the version string of the failing macOS awk?

**Comment by step-** [comment]
Is the failed test output by docker-test? I ran docker-test on linux only. Do I need to run docker-test also on macOS for a complete test?

**Comment by junegunn** [comment]
> if you're still interested in this patch. Are you?

I don't personally need it, but if it works and it doesn't do any harm, then why not?

> What's the version string of the failing macOS awk?

```
$ awk --version
awk version 20200816
```

> Is the failed test output that you included by docker-test?

No, I just manually tested it on my macbook. Everything is shown as a single item.

image

**Comment by step-** [comment]
I tried, but failed, to make this commit work with the default awk version for macOS.  Thinking out of the box, I decided to try a bash-only solution instead, which is now PR #3310.  This PR can be closed.  It works on Linux, but fails on macOS unless GNU awk (or mawk / busybox awk) is installed.

**Pull request closed without merging**
