### PR TITLE
[WIP] Multiline Ctrl-r in fish

### PR DESCRIPTION
**Pull request by tomfitzhenry**
https://github.com/junegunn/fzf/issues/436

Todo:
- [ ] Don't hardcode `~/.config/fish/fish_history`

### CODE REVIEW

**Comment by tomfitzhenry** [comment]
I'm beginning to think the poor multiline handling is a bug against fish's `history`, and that we shouldn't work around it in `fzf`. I'll raise this in `fish`.

**Comment by junegunn** [comment]
Thanks for looking into this. Note that `tac` is not available on OS X and `tail -r` can be used instead.

**Comment by leiserfg** [comment]
fish_history can   be on ~/.local/share/fish/fish_history   too.

**Comment by tomfitzhenry** [comment]
Closing, in favour of https://github.com/junegunn/fzf/pull/954

**Pull request closed without merging**
