### PR TITLE
Fix Bash+vimode pre-launch delay

### PR DESCRIPTION
**Pull request by WChargin**
Summary:
Fix from: https://adamheins.com/blog/fzf-vi-mode-and-fixing-delays
(Thanks, @adamheins!)
The basic problem is that
fzf presses <Esc> to enter vi-movement-mode
(as opposed to insert mode)
and then presses a bunch of keys to set up the buffer.
But the <Esc> keypress is also the prefix for a bunch of other commands,
so Bash will dutifully wait an excruciating half-second
before actually executing this command.
Instead, we bind <C-a>, which is unused by default,
to be another way to enter vi-movement-mode;
this binding is unambiguous, so fzf can use it without delay.

This change was made by just `:s/\\e/\\C-a/gc` in the relevant section,
after adding the actual binding and comment at the top.

### CODE REVIEW

**Comment by junegunn** [comment]
Interesting, thank you. Looks like it only happens with bash 4+. How about if we choose a more obscure key that is less likely to be used by the users, such as `\C-x\C-a` or something? I'm saying this because there can be users who mapped `\C-a` to something else.

And `bind '"\C-ac":` seems like a mistake, right?

**Comment by WChargin** [comment]
Yep, good call on both. (I didn't know `<Esc>c` would `cd`—nice!)

**Comment by WChargin** [comment]
Actually, I'm not sure what the line `bind -m vi-command '"\ec": "i\ec"'` is supposed to do. Is it supposed to let you use `<Esc>c` when you're not in insert mode? This doesn't work for me even before this patch (on `origin/master` 935e986be5fe3d6c9ca6fa578d836500a3b31525).

**Comment by junegunn** [comment]
> Is it supposed to let you use `<Esc>c` when you're not in insert mode? 

Yes.

> This doesn't work for me even before this patch

Interesting. CTRL-R and CTRL-T work as expected but not ALT-C. Do you have any clue?

**Comment by WChargin** [comment]
Nope, I don't know; I've never touched `bind` before. I do note that inlining it, as follows, works:
```sh
  bind '"\ec": "\C-x\C-addi$(__fzf_cd__)\C-x\C-e\C-x\C-r\C-m"'
  bind -m vi-command '"\ec": "ddi$(__fzf_cd__)\C-x\C-e\C-x\C-r\C-m"'
```
(Note that I removed the extra `\C-x\C-a` at the beginning of the mapping.)

So my guess was that it was a non-recursive mapping, but that doesn't appear to be the case: I ran
```sh
bind '"\C-j": "abcde"'
bind -m vi-command '"\C-i": "i\C-j"'
```
and then pressing `<C-i>` in normal mode did cause the characters to be inserted.

If you're comfortable with the patch in the first snippet, I'll push it.

**Comment by WChargin** [comment]
(Could you reproduce, by the way, on master?)

**Comment by junegunn** [comment]
Yeah, that works :)

**Comment by WChargin** [comment]
Okay, I went ahead and squashed down the commits to two (one for each fix).

**Comment by junegunn** [comment]
Merged, thanks!

**Pull request merged**
