### PR TITLE
fallback to fzf when tmux pane is zoomed.

### PR DESCRIPTION
**Pull request by amosbird**

### CODE REVIEW

**Comment by junegunn** [comment]
Have you taken a look at #433? We already handle zoomed panes.

(By the way, I just noticed a bug with the loging handling `-l` `-u` on zoomed panes. Let me push the fix for it.)

**Comment by amosbird** [comment]
well, it seems not working on my env. `fzf-tmux` just deletes all the panes when finished.

**Comment by junegunn** [comment]
Can you check if 1ba7acf4bd4314f299b57cea73cbd376bde5aba3 helps?

**Comment by amosbird** [comment]
no, it doesn't help.

**Comment by amosbird** [comment]
I'm using latest tmux, configuration is in https://github.com/amosbird/tmuxconfig

**Comment by junegunn** [comment]
Looks like you're a fish user, so I believe #891 fixes the issue you experience.

**Pull request closed without merging**
