### PR TITLE
improving fish script 

### PR DESCRIPTION
**Pull request by leiserfg**

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks. We have to make the following prefixes work correctly with ctrl-r:
- `echo $PATH`
- `echo $(`
- `echo 'foo`
- `echo "foo`
- `echo -e "foo\nbar"`
- `echo -e "foo\rbar"`

**Comment by leiserfg** [comment]
Last commit works with substitutions but not with quotes. I'm working on it.

**Comment by leiserfg** [comment]
It's failing because  I remove the temporal dir on the script but not on the installer. Letter I'll write a way to use multilines completions with ctrl+r. Now it's time for me to lunch :D

**Comment by junegunn** [comment]
No hurries :)

**Comment by kopischke** [comment]
Heck of a lunch pause. Snark apart, how is the status on this?

**Pull request closed without merging**
