### PR TITLE
Add an option: --tty=DEVICE

### PR DESCRIPTION
**Pull request by knu**
I have a similar problem to #447, where tty is somehow inaccessible via /dev/tty but $TTY still points to the working tty.  In this case, you could say `fzf --tty=$TTY` to force attaching to the tty.

In my case, I tried to invoke fzf from within rb-readline on Rails console run under spring, but I got the `Failed to open /dev/tty` error.  I guess there could be something wrong with the handling of tty in any of pry/spring/rb-readline, but I wasn't able to identify which and how.

### CODE REVIEW

**Comment by junegunn** [comment]
Can you provide the repro steps? I'd like to make sure that the problem is reliably reproducible and there's absolutely no workaround for the issue.

**Comment by knu** [comment]
Sure, here it is.  In the following environment I have:

- macOS 10.13.4 (High Sierra; the version would not matter)
- Ruby 2.4.4 installed via rbenv (Any version >= 2.2 will do)

Put the following in `~/.pryrc`:

```ruby
begin
  require 'rb-readline'
  require 'readline'
rescue LoadError
else
  def RbReadline.rl_reverse_search_history(sign, key)
    rl_insert_text `fzf --no-sort --tac < ~/.pry_history`.chomp
  end
end
```

Then create a Rails project and add Pry and Spring to it:

```
% gem install rails -v 5.2.0

% rails new foo

% cd foo
% echo "gem 'pry-rails', group: :development" >> Gemfile
% echo "gem 'rb-readline', group: :development" >> Gemfile
% bundle
```

Finally, run rails condole under Spring and invoke fzf via <key>^R</key> in the Pry prompt:

```
% spring rails condole
Running via Spring preloader in process 52196
Loading development environment (Rails 5.2.0)
[1] pry(main)> <^R>Failed to open /dev/tty
```

Passing `--tty=$TTY` to the patched fzf, to get it to open `$TTY` instead of `/dev/tty`, fixes the issue.

**Comment by junegunn** [comment]
Thanks for the repro, I was able to reproduce the problem on `rails console`. By the way, `$TTY` is not set on my shell, do you set it manually?

Since fzf requires that STDERR is a tty device, we can find the name of the actual device via `ttyname(2)`. But fzf no longer uses `cgo` and we have to implement our own version of the function. I can confirm that the following patch fixes the issue on macOS and Linux, though I haven't tested it on other platforms such as FreeBSD or OpenBSD yet.

```diff
diff --git a/src/tui/light.go b/src/tui/light.go
index a96a844..e223f4a 100644
--- a/src/tui/light.go
+++ b/src/tui/light.go
@@ -32,6 +32,12 @@ var offsetRegexp *regexp.Regexp = regexp.MustCompile("\x1b\\[([0-9]+);([0-9]+)R"
 func openTtyIn() *os.File {
 	in, err := os.OpenFile(consoleDevice, syscall.O_RDONLY, 0)
 	if err != nil {
+		tty := ttyname()
+		if len(tty) > 0 {
+			if in, err := os.OpenFile(tty, syscall.O_RDONLY, 0); err == nil {
+				return in
+			}
+		}
 		fmt.Fprintln(os.Stderr, "Failed to open "+consoleDevice)
 		os.Exit(2)
 	}
diff --git a/src/tui/ttyname_unix.go b/src/tui/ttyname_unix.go
new file mode 100644
index 0000000..69bdfa5
--- /dev/null
+++ b/src/tui/ttyname_unix.go
@@ -0,0 +1,31 @@
+// +build !windows
+
+package tui
+
+import (
+	"io/ioutil"
+	"syscall"
+)
+
+var devPrefixes = [...]string{"/dev/pts/", "/dev/"}
+
+func ttyname() string {
+	var stderr syscall.Stat_t
+	if syscall.Fstat(2, &stderr) != nil {
+		return ""
+	}
+
+	for _, prefix := range devPrefixes {
+		files, err := ioutil.ReadDir(prefix)
+		if err != nil {
+			continue
+		}
+
+		for _, file := range files {
+			if stat, ok := file.Sys().(*syscall.Stat_t); ok && stat.Rdev == stderr.Rdev {
+				return prefix + file.Name()
+			}
+		}
+	}
+	return ""
+}
diff --git a/src/tui/ttyname_windows.go b/src/tui/ttyname_windows.go
new file mode 100644
index 0000000..5354b74
--- /dev/null
+++ b/src/tui/ttyname_windows.go
@@ -0,0 +1,7 @@
+// +build windows
+
+package tui
+
+func ttyname() string {
+	return ""
+}
```

**Comment by junegunn** [comment]
I was a bit concerned about the performance of the`ttyname` implementation, but I can't notice any delay from the code, so I'm going to apply the patch instead of adding `--tty`. Let me know if you see any issues. Thanks.

**Comment by knu** [comment]
Ah, it might look a little bit tricky but would work for most well-known unix-like systems including FreeBSD and OpenBSD.

**Comment by junegunn** [comment]
Yeah, and the code is only for exceptional cases, so I think it's enough.

**Pull request closed without merging**
