### PR TITLE
[vim] Encode list source to codepage

### PR DESCRIPTION
**Pull request by janlazo**
Followup on https://github.com/junegunn/fzf/commit/f68017d21e78b23fbf648d579edb6500ae7a6de8#commitcomment-36437403

After this, all `fzf.vim` commands must be updated to not use truecolor formatting on Windows. Need more testing to verify if `iconv` is really needed. Maybe it's required for (g)vim only.

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks again.

> fzf.vim commands must be updated to not use truecolor formatting on Windows

So you mean we need an equivalent change to aa0e10ead71cd9995bf6d6a01799e52551895816 in `s:get_color` here?

**Comment by janlazo** [comment]
> > fzf.vim commands must be updated to not use truecolor formatting on Windows
> 
> So you mean we need an equivalent change to [aa0e10e](https://github.com/junegunn/fzf/commit/aa0e10ead71cd9995bf6d6a01799e52551895816) in `s:get_color` of fzf.vim?

Yes. This restriction can be loosened for ConEmu and other Windows terminals that support truecolor after https://github.com/junegunn/fzf/pull/1341 is merged.

**Comment by junegunn** [comment]
Thanks, do you think #1341 is ready for merge?

**Comment by janlazo** [comment]
> Thanks, do you think #1341 is ready for merge?

Yes for `--height`.

**Pull request merged**
