### PR TITLE
don't install zsh files if zsh doesn't exist

### PR DESCRIPTION
**Pull request by adam8157**
as $subject. keep bash files since it's almost preloaded everywhere.

### CODE REVIEW

**Comment by netei** [comment]
it is recommended not to use which. You should rather use `command -v`

Like so : 

```
if [ $shell = "zsh" ] && ! command -v zsh >/dev/null; then
```

**Comment by junegunn** [comment]
Thanks for the suggestion, I'll update the code myself to keep the style consistent across the file.

@netei Didn't know that. Thanks for the info.

**Comment by junegunn** [comment]
Fixed it. Let me know if you see any issues, thanks.

**Comment by adam8157** [comment]
Cool. Better to fix uninstall script too, thanks.

**Pull request closed without merging**
