### PR TITLE
use read syscall directly to get character

### PR DESCRIPTION
**Pull request by tw4452852**
Fix issue #910 .

### CODE REVIEW

**Comment by junegunn** [comment]
Thanks, I'd prefer to have the comment as the commit message, can you move it?

**Comment by tw4452852** [comment]
Done.

**Comment by junegunn** [comment]
Oh well, it doesn't compile for Windows.

```
> GOOS=windows make release
cd /Users/jg/.vim/plugged/fzf/gopath/src/github.com/junegunn/fzf/src && go get -tags ""
# github.com/junegunn/fzf/src/tui
tui/light.go:256: cannot use fd (type int) as type syscall.Handle in argument to syscall.Read
make: *** [deps] Error 2
```

We might need to move getch code to util_unix and util_windows.

**Comment by tw4452852** [comment]
Hmm, I just work out `syscall.Read` for different platforms instead.

BTW, `light.go` isn't for windows apparently, because it gets input from `/dev/tty` which doesn't exist on windows. For now, we disable `--height` option on windows, so `LightRenderer` won't be used on windows. I think we should add `+build !windows` to `light.go`.

**Comment by junegunn** [comment]
Thanks, you're right, I think it's good enough for now. I'll merge your commit to devel branch first.

**Pull request merged**
