### PR TITLE
make fzf work in standard Git Bash Term

### PR DESCRIPTION
**Pull request by Konfekt**
Script provided by @knutze

Addresses https://github.com/junegunn/fzf/issues/2798

### CODE REVIEW

**Comment by junegunn** [comment]
The approach looks quite similar to what we've been doing in [fzf-tmux](https://github.com/junegunn/fzf/blob/master/bin/fzf-tmux), and the script was recently rewritten in [native Go code](https://github.com/junegunn/fzf/pull/3787). I'll see if we can do the same for this. If that's possible,

* it will work without extra configuration
* it will work not just on bash, but also on other shells

**Comment by junegunn** [comment]
Can you test 573df524fed1c493ce7d8ea893f06ab90f2ca18a? It seems to work for me fine. Because it's using named pipes, it doesn't block even when the source command takes a while to complete.

```sh
./fzf
ls | ./fzf
(sleep 5; ls) | ./fzf
```

Attaching the binary built from the source.

[fzf.exe.zip](https://github.com/junegunn/fzf/files/15375382/fzf.exe.zip)

**Comment by Konfekt** [comment]
I can confirm that this release works fine in Git Bash Term under Windows 10 without the bash script work around.
(It works also fine with the Bash work around. Removing the new exe, the pipe is broken again.)

**Comment by junegunn** [comment]
Cool, I'll close this then and include the patch in the next release.

**Pull request closed without merging**
